import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import { NavBar } from "@/components";

const PPEditorial = localFont({ src: './fonts/PPEditorialNew-Ultralight.otf' })
const PPEditorialItalic = localFont({ src: './fonts/PPEditorialNew-UltralightItalic.otf' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PPEditorial.className} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
